[package]
name = "isp3080-test"
version = "0.1.0"
edition = "2018"

[dependencies]
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
nrf52833-hal = "0.18.0"
panic-semihosting = "0.6.0"
usb-device = "0.3.2"
usbd-serial = "0.2.1"
